### ISSUE TITLE
Quick start tips...

### ISSUE THREAD

**Issue by hlogmans** [priestjim/chef-phpmyadmin#15]
Thanks priestjim for your cookbook. As quite a beginner, a had some hassles to get things up and running, but still it does not work... I'm working on a Ubuntu 14.04 with apache2 + mysql system, following the [third chef tutorial](https://learn.chef.io/manage-a-web-app/ubuntu/configure-php/#). Maybe some information could be added to the readme to help new Chef users a bit further to get a minimal setup up and running.

In my recipe, I have added the following to setup php and phpmyadmin
Berksfile:

````
source 'https://supermarket.chef.io'

metadata
cookbook 'application_ruby', git: 'https://github.com/poise/application_ruby.git'
cookbook 'passenger_apache2', git:'https://github.com/hlogmans/passenger_apache2.git'
cookbook 'phpmyadmin', git: 'https://github.com/priestjim/chef-phpmyadmin.git'
cookbook 'php', git: 'https://github.com/priestjim/chef-php.git'

````
Then  in the metadata.rb the correct depends.

In the recipe, these recipes are called (after setting up mysql & ruby application, those work fine):

include_recipe "php::default"
include_recipe "php::fpm"
include_recipe "phpmyadmin::default"

phpmyadmin_db 'Test DB' do
  host '127.0.0.1'
  port 3306
  username 'root'
  password root_password_data_bag_item['password']
  hide_dbs %w{ information_schema mysql phpmyadmin performance_schema }
end

**But with only above information, I have no clue how to access PhpMyAdmin using the browser. Is it integrated into Apache or not?**

So I went on and created a virtual host for PMA (port 81), and then the php page is displayed (uncompiled php that is). So I presumed Apache has no clue about PHP. 
To solve this, I followed the instructions in the earlier mentioned tutorial:
````
# Install the mod_php5 Apache module.
include_recipe 'apache2::mod_php5'

# Install php5-mysql.
package 'php5-mysql' do
  action :install
  notifies :restart, 'service[apache2]'
end
```` 

At first start, I now can access PMA using (host):81, but the actual login to mysql fails. When I try to restart apache by using `sudo service apache2 restart` I get the config warning `Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.` Probably there are two versions of PHP interfering with each other?

*Update*

As an alternative I removed all FPM and Ruby/application stuff. Added the 'php::apache2' include, and switched to 
````
phpmyadmin_pmadb 'Test DB' do
  host '127.0.0.1'
  port 3306
  root_username 'root'
  root_password root_password_data_bag_item['password']
  pma_database 'phpmyadmin'
  pma_username 'root'
  pma_password 'silly4nothing'
  #hide_dbs %w{ information_schema mysql phpmyadmin performance_schema }
end
````

In MySQL I can see the created database (phpmysql), it has tables but no users. I cannot login using any credentials, and after doing a apache restart I get the MPM message again :(

**Comment by hlogmans** [comment]
OK, got it up and running: (Ubuntu 14.04, Apache 2.4.7

1. Set some defaults: add port 81 to apache, disable FPM and set Apache2 to prefork
````
default['apache']['listen_ports'] = %w(80 81 443)
default['phpmyadmin']['fpm'] = false

default['apache']['mpm'] = 'prefork' # force it
````

2. Install Apache, PHP
`````
include_recipe 'apache2::default'
include_recipe "php::default"
include_recipe "php::apache2"
include_recipe "phpmyadmin::default"
`````

3. Add an apache config file
`````
<VirtualHost *:81>
  DocumentRoot /opt/phpmyadmin

  <Directory /opt/phpmyadmin>
    Options FollowSymLinks
    AllowOverride All
    Require all granted

  </Directory>

</VirtualHost>
```` 
and in the recipe (use 127.0.0.1 instead of localhost to bypass different socket naming)
````
phpmyadmin_db 'Test DB' do
  host '127.0.0.1'
  port 3306
  username 'root'
  password root_password_data_bag_item['password']
  auth_type 'cookie'
  hide_dbs %w{ information_schema mysql phpmyadmin performance_schema }
end

web_app "phpmyadmin" do
  template "phpmyadmin.conf.erb"
end

# if needed, in cookbook firewall
firewall_rule 'http' do
  port 81
  protocol :tcp
  action :allow
end
````

Now there is one problem left: the generated file in the conf.d folder needs to be world readable, it is only group readable. So chmod it to 644.

With this setup, go to <server>:81 and have fun logging in with your mysql credentials.

**Comment by priestjim** [comment]
Glad you figured it out! In my opinion, PHP should be optimally ran through NGINX+FPM hence my support only for that scenario!
