### ISSUE TITLE
phpmyadmin in Vagrant

### ISSUE THREAD

**Issue by fulloflilies** [priestjim/chef-phpmyadmin#23]
Hi,

I installed phpmyadmin in Vagrant synced_folder with owner: www-data and mount_options: ["dmode=751,fmode=777"] 
When I opened phpmyadmin with browser, it made error as below 

```
phpMyAdmin - Error
Wrong permissions on configuration file, should not be world writable!
```

I manually added following in config.inc.php to workaround and it is working

```
$cfg['CheckConfigurationPermissions'] = false;
```

Would it be better way to fix this issue?

**Comment by priestjim** [comment]
Why would you need the phpmyadmin folder as a synced folder in the first place? What's your use case?

**Comment by fulloflilies** [comment]
The syncd_folder is to connect development code files to Vagrant in my use case. phpmyadmin is part of the development files so included here. 
I could install phpmyadmin outside of the synced_folder, but it would be different configuration from production environment so wanted to run phpmyadmin in the same place as production.

**Comment by priestjim** [comment]
I added a config option so you can disable the warning :)
