### ISSUE TITLE
default is missing mbstring

### ISSUE THREAD

**Issue by jpratt3000** [priestjim/chef-phpmyadmin#24]
when running the recipe I receive: 

ala-rntdbeo.wrs.com ================================================================================
ala-rntdbeo.wrs.com Recipe Compile Error
ala-rntdbeo.wrs.com ================================================================================
ala-rntdbeo.wrs.com
ala-rntdbeo.wrs.com Chef::Exceptions::RecipeNotFound
ala-rntdbeo.wrs.com --------------------------------
ala-rntdbeo.wrs.com could not find recipe module_mbstring for cookbook php
ala-rntdbeo.wrs.com
ala-rntdbeo.wrs.com Cookbook Trace:
ala-rntdbeo.wrs.com ---------------
ala-rntdbeo.wrs.com   /var/chef/cache/cookbooks/phpmyadmin/recipes/default.rb:26:in `from_file'

**Comment by priestjim** [comment]
You need to use the chef-php repo from https://github.com/priestjim/chef-php!

**Comment by jpratt3000** [comment]
i am.

**Comment by jpratt3000** [comment]
cookbook "php", github: "priestjim/chef-php"

via the berks file

**Comment by priestjim** [comment]
Have you verified it's actually using that php cookbook? It's possible to have uploaded my cookbook and the official cookbook to the Chef server and the official cookbook has its version bigger than mine which overrides my cookbook!

**Comment by jpratt3000** [comment]
yes its using the 1.2.3 version of chef-php, but appears to be complaining about chef-yumrepo which has been deprecated for yum-corporate...

using berks, shouldn't all of the correct recipes been pulled in?

**Comment by priestjim** [comment]
Yeah they should. Have you done a `knife cookbook show php`? It should only show php 1.2.3.

**Comment by gloaec** [comment]
It's maybe a bit late, but if it can help anyone out. You must indeed update your `Berkfile` so it uses _priestjim_'s version of the cookbook : 

    cookbook "php", github: "priestjim/chef-php"

But you also need to delete the `Berkfile.lock` for the dependency to be actually updated. 
Hope this helps, cheers !
